### ISSUE TITLE
mate-tweak doesn't show some panel layouts since version 17.10.7 and later on arch/manjaro

### ISSUE THREAD

**Issue by ThanosApostolou** [ubuntu-mate/mate-tweak#27]
mate-tweak 17.10.6:
![screenshot at 2017-07-27 22-12-39](https://user-images.githubusercontent.com/21288843/28687947-d403004a-7318-11e7-92c8-fb0c2559c788.png)

mate-tweak 17.10.7, 17.10.8, 17.10.9:
![screenshot at 2017-07-27 22-11-21](https://user-images.githubusercontent.com/21288843/28687962-e6190b30-7318-11e7-9da1-32b12eead63b.png)

The pkgbuild copies the additional layouts from the **ubuntu-mate-settings 17.10.17** package. I see some changes at the commits after **mate-tweak 17.10.6**, but I cannot understand how to fix this. Is the way mate-tweak recognizes panel layouts different now?

**Comment by flexiondotorg** [comment]
MATE Tweak will only show layouts the host distro supports. So of the layouts shipped by Ubuntu MATE now require [vala-panel-appmenu](https://github.com/rilian-la-te/vala-panel-appmenu) and [several indicators](https://github.com/ubuntu-mate/mate-tweak/blob/master/mate-tweak#L1023) to function.

**Comment by ThanosApostolou** [comment]
Thx for the info. I'll contact Stefano (manjaro's mate maintainer) and ask him to see if he can include these in manjaro.

**Comment by ThanosApostolou** [comment]
@flexiondotorg It seems like a lot of effort to include all these indicators in Manjaro (and the rest arch based distros). So, maybe you are willing to create some basic additional panel layouts like for example **redmond (no indicators)** which will not require these indicators for the arch based distributions?

**Comment by flexiondotorg** [comment]
In which case it might be better if Manjaro creates the layouts they want and adds them to list MATE Tweak looks for 😀

**Comment by ThanosApostolou** [comment]
Hmmm... that way, thought, it wouldn't help the other arch based distributions... :disappointed:  Arch and Artix will have the package from AUR. Antergos has its own mate-tweak build. Revenge os has its own mate-tweak build. So, it would be really nice if you could make it somehow, to show some simple panel layouts like redmond without the need of indicators, in case the indicators are missing (probably it can be done by modifying the if statements in the mate-tweak code). Otherwise, the same work has to be done multiple times by each maintainer (and I believe that there are more distributions which don't have indicators like Solus, Fedora, mandriva, debian...).

Of course I understand that mate-tweak is destined primarily for Ubuntu MATE, so I understand if you still don't want to do it.

**Comment by flexiondotorg** [comment]
What I'm saying is you don't need to rely on me to create the layouts you'd like ☺️ If there is a selection of layouts you've identified that would suit Manjaro and other Arch distro (or any other disto for that matter) then please so create those layouts and we can add support for them in MATE Tweak. For example, layouts for Fedora and Solus are already supported by MATE Tweak.
