### ISSUE TITLE
Add a "Don't show this message again" checkbox on the changing layouts message.

### ISSUE THREAD

**Issue by Neverest** [ubuntu-mate/mate-tweak#29]
Every time you want to change the panel layout in Mate Tweak you get a message saying "Replacing the panel layout is a  destructive operation! etc", it would be nice if you added a checkbox with "Don't show this message again" so one can change the layouts quicker.

**Comment by flexiondotorg** [comment]
The capability is available via:

- Executing `mate-tweak --layout <layoutname>` in a terminal.
- Or via Ubuntu MATE Welcome which can switch layouts without user prompting.
