### ISSUE TITLE
Manjaro: mate-compton doesn't autostart

### ISSUE THREAD

**Issue by ThanosApostolou** [ubuntu-mate/mate-tweak#30]
If you choose **marco-compton** as Window Manager at Mate Tweak then it works fine. However, after logout and login the window manager doesn't autostart. Both **~/.xsession-errors** and journalctl show the error:
```
WARNING: Unable to find provider 'marco-compton' of required component 'windowmanager'
```
Dconf-editor shows that **/org/mate/desktop/session/required-components** is set to **marco-compton**. Mate-tweak provides the file **/usr/bin/marco-compton**, but apparently it's not enough in order to get recognized by mate session? I couldn't find any info or couldn't understand any differences when comparing it with Ubuntu MATE... Do we need to include anything extra in manjaro in order to make marco-compton work?

**Comment by ThanosApostolou** [comment]
Ok the problem gets fixes if I copy the desktop entries from **/usr/share/mate/applications** to **/usr/share/applications**. So, I will do the changes in the PKGBUILD to copy those files there. However, it would be nice if you have free time to explain why this isn't needed in Ubuntu MATE, but it's needed in Manjaro.

Have you done any patches in order to work in Ubuntu MATE out of the box, or is it something else going on with Manjaro? The **/usr/bin/mate-wm** has a comment which says that a window manager need to provide a desktop file in order to get recognized, but it doesn't say where. Is it supposed to get recognized directly from **/usr/share/mate/applications** or they need to be placed under **/usr/share/applications** (if not how is this done in Ubuntu MATE?)?

I close this, but if you have any free time please give me as much info as you can.

**Comment by flexiondotorg** [comment]
`.desktop` files present in `/usr/share/mate/applications` are only available when a MATE desktop session is running. A useful way to provide application entries specific to MATE :-)

I'm not sure why Manjaro is unable to process file in `/usr/share/mate/applications`, I'm not aware of doing anything to make that work.

**Comment by ThanosApostolou** [comment]
Hmmm I see, thx for the info. It seems like it needs more digging.

**Comment by ThanosApostolou** [comment]
@flexiondotorg I tested on Fedora too and it seems that desktop launchers at **/usr/share/mate/applications** are not recognized. This seems to only work on Ubuntu MATE (maybe debian too, I haven't tested there yet). So, maybe you can change the installation script and put the desktop files at **/usr/share/applications** instead of **/usr/share/mate/applications** by default?

**Comment by flexiondotorg** [comment]
Closed via https://github.com/ubuntu-mate/mate-tweak/commit/c9e3bd8fd6882f524aec7252baffaada4fdd7e93
