### ISSUE TITLE
Mate-Tweak: setting the default system-wide layout

### ISSUE THREAD

**Issue by devbie** [ubuntu-mate/mate-tweak#32]
Hi,

(I originally posted this on the Ubuntu Mate IRC channel where it was suggested I should post it here. It's my 1st posting in Github, please excuse me if this isn't quite the right place for the posting)

I'm using Ubuntu Mate 16.04 LTS. I'd like to set a modified version of one of the available desktop layouts as the system-wide default layout (I want to add the 'log out' applet to the top panel)

I've already modified the layout for the current (admin) user. Now, I'd like to make it the default layout for all new user accounts. At the moment I am having to set it up manually each time I open a new account. It would be nice to be able to automatically apply the modified default layout to new user accounts.

Can this be done? Or this is going to turn to a feature request?

Many thanks

**Comment by flexiondotorg** [comment]
Yes, you can create a gschema override file, like this:

```bash
sudo nano /usr/share/glib-2.0/schemas/90_ubuntu-mate-default-layout.gschema.override
```

Add the following, but change `familiar` to the name of the layout you want to be the system default:

```ini
[org.mate.panel]
default-layout='familiar'
```

Now rebuild the schemas:

```bash
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```
