### ISSUE TITLE
Mate-tweak not show some layout

### ISSUE THREAD

**Issue by Ste74** [ubuntu-mate/mate-tweak#35]
Hi there, i have updated the program on the last stable release but i can't see in the gui the layout.
I build it for Manjaro
[here](https://github.com/manjaro/desktop-settings/tree/master/community/mate/layouts) the layouts build for Manjaro
and [here](https://github.com/manjaro/packages-community/blob/master/mate/mate-tweak/PKGBUILD) the pkgbuild for mate-tweak.
I don't understand .. via terminal i can switch via 
`mate-tweak --layout manjaro `
but in the gui i can see only 
```
fedora
gnome2
traditional
redmond
```
i missed something

Stefano
Manjaro Team

**Comment by Ste74** [comment]
Sorry for this UP but not understand why at now the manjaro.layout and other layouts installed via arch/manjaro  are not recognized since here the support are done
https://github.com/ubuntu-mate/mate-tweak/commit/89cd76326eedc2898a4b108a2a956cc2170d1b50
At now we cans see only `fedora, default and opensuse`

**Comment by vkareh** [comment]
Are you maybe missing the indicators packages?

**Comment by Ste74** [comment]
Hi @vkareh, thank you  for take a look here. Tried to install mate-indicator-applet but this don't help..
How debug mate-tweak to find what is missing or what we have wrong?

**Comment by Ste74** [comment]
Uhm .. i see this https://ubuntu-mate.community/t/i-am-missing-panel-layouts-in-mate-tweak-after-updating-to-18-04/16694/4 ... and i see your answer and solution. So what provides the `mate-applet-brisk-menu`? I see into launchpad repo but i see only a `brisk-menu` code.. Manjaro already ships with `brisk-menù` as default.. I'm confused :roll_eyes:

**Comment by Ste74** [comment]
Ok, find some free time to investigate into it.. this PR solve my issue
https://github.com/ubuntu-mate/mate-tweak/pull/68
only don't know where are locate other layouts like cupertino o mutinity or how you check this
in arch/manjaro as i said in the PR comment the brisk-menu path is wrong..

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-tweak/releases/tag/20.10.0
