### ISSUE TITLE
mate tweak doesn't work with latest marco commits

### ISSUE THREAD

**Issue by ThanosApostolou** [ubuntu-mate/mate-tweak#40]
message when running mate-tweak;
```
Window Manager is: marco

(mate-tweak:12777): GLib-GIO-ERROR **: Settings schema 'org.mate.Marco.general' does not contain a key named 'side-by-side-tiling'
Trace/breakpoint trap
```

I think the responsible commit is this: https://github.com/mate-desktop/marco/commit/709fe3eb2f8987ffc598ecbece4997acdf51cdca. I don't know where mate-tweak is using this, but it would be nice if you can implement something to fix it for those who running git packages (soon to be released, if I've understood correctly) without breaking it for those who are using to old releases.

**Comment by perkinsjs83** [comment]
The same error is happening still in the 1.20 release of the Mate Desktop that came out today.

Window Manager is: marco

(mate-tweak:9397): GLib-GIO-ERROR **: Settings schema 'org.mate.Marco.general' does not contain a key named 'side-by-side-tiling'
Trace/breakpoint trap
