### ISSUE TITLE
Doesnt start after update to Mate v1.20

### ISSUE THREAD

**Issue by Ntemis** [ubuntu-mate/mate-tweak#42]
Gtk-Message: Failed to load module "unity-gtk-module"

(mate-tweak:25953): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:6:27: The style property GtkPaned:handle-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(mate-tweak:25953): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1719:28: The style property GtkRange:slider-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(mate-tweak:25953): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1720:29: The style property GtkRange:trough-border is deprecated and shouldn't be used anymore. It will be removed in a future version
Window Manager is: marco
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 1682, in <module>
    MateTweak()
  File "/usr/bin/mate-tweak", line 1518, in __init__
    self.builder.get_object("checkbox_localmenu").set_active(self.show_localmenu)
AttributeError: 'MateTweak' object has no attribute 'show_localmenu'

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-tweak/pull/41

**Comment by Ntemis** [comment]
Confirm, thanks :)
