### ISSUE TITLE
Adjust HiDPI scaling factor?

### ISSUE THREAD

**Issue by nonfatmatt** [ubuntu-mate/mate-tweak#44]
I have been enjoying MATE on a 1440p monitor which leaves me in a hard place with regards to scaling.  Without scaling everything is too small and with it, everything too big.  It would be nice to have a slider for a variable level so you can tweak MATE for whatever HiDPI panel you have.

**Comment by vkareh** [comment]
@nonfatmatt - yeah, this is a tricky one. GTK+ only supports integer-level scaling (1, 2, 3, ...) so we can't scale at, say, 1.5x... However, the trick for this is to scale to 2 (HiDPI) and bring your font size down (go to Appearance > Fonts > Details... and set to something like 144). Let me know how this works out for you.

**Comment by nonfatmatt** [comment]
That works for me, thanks. 
What might be nice would be to have the DPI also show up in Mate Tweak Tool, but I'm not sure how you feel about overlapping functionality.  I didn't know it was an option in MATE until you informed me. In XFCE it's pretty obvious that there is a custom DPI setting but in Mate it's buried under "details."

**Comment by vkareh** [comment]
Good, I'm glad it worked :)

Yeah, maybe we should add a link to the DPI settings somewhere there, as they are often related settings. But I also don't want to overwhelm the users with too many settings... Maybe in the description text, where it says "_Select a window scaling factor._", we can change it to "_Select a window scaling factor. You can also &lt;link&gt;adjust the font DPI&lt;/link&gt;._", and the user can click that link to open the font settings dialog.

**Comment by flexiondotorg** [comment]
It is possible to open the Fonts tab in `mate-appearance-properties` directly, but not the *Details...* where the font DPI can be adjusted. That is better than nothing.

@vkareh If I were to add a font DPI spinner to MATE Tweak do I need to do anything special?

**Comment by vkareh** [comment]
@flexiondotorg - nope, just change `org.mate.font-rendering dpi`. Keep in mind that the default is 0 and once the user changes it they would need to use gsettings/dconf to reset it (I'm working on a toggle for this on the _Details..._ dialog)

**Comment by flexiondotorg** [comment]
In which case, probably best to direct people to the Fonts tab and explain they are looking for *Details...* I'm not a fan of duplicating where options are configured.

**Comment by vkareh** [comment]
I agree. I think directing the user makes sense. I can try figure out a way of auto-opening the Details dialog (some code change in m-c-c to support this)

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-tweak/commit/fbf7bfd0da4d48382880208e5ad90da25d647620
