### ISSUE TITLE
HiDPI settings are not applied upon login with nvidia proprietary drivers

### ISSUE THREAD

**Issue by shigutso** [ubuntu-mate/mate-tweak#45]
Ubuntu MATE 18.04 LTS x86_64
nvidia-396 drivers
1920x1080 display

On opensource drivers it works fine, but it seems that the proprietary nvidia drivers does something that prevents the HiDPI settings to be applied when a user logins.

Is there any way to fix that? Or at least is there a mate-tweak command line options to set HiDPI settings so I can automate as a workaround?

Also found this bug report with another workaround:
https://ubuntu-mate.community/t/scaling-issues-with-nvidia/14801
But it's not a very graceful way to fix things...

Thanks

**Comment by flexiondotorg** [comment]
please run `ubuntu-report show` and paste the output here.

**Comment by vitorgatti** [comment]
```
{
  "Version": "18.04",
  "OEM": {
    "Vendor": "Alienware",
    "Product": "Alienware 14"
  },
  "BIOS": {
    "Vendor": "Alienware",
    "Version": "A09"
  },
  "CPU": [
    {
      "Vendor": "GenuineIntel",
      "Family": "6",
      "Model": "60",
      "Stepping": "3"
    }
  ],
  "Arch": "amd64",
  "GPU": [
    {
      "Vendor": "10de",
      "Model": "11e2"
    }
  ],
  "RAM": 16.3,
  "Partitions": [
    19.1,
    0.1,
    441.2
  ],
  "Screens": [
    {
      "Resolution": "1920x1080",
      "Frequency": "60.05"
    }
  ],
  "Autologin": false,
  "LivePatch": false,
  "Session": {
    "DE": "MATE",
    "Name": "mate",
    "Type": "x11"
  },
  "Timezone": "America/Sao_Paulo",
  "Install": {
    "Media": "Ubuntu-MATE 18.04 LTS \"Bionic Beaver\" - Release amd64 (20180426)",
    "Type": "GTK",
    "PartitionMethod": "manual",
    "DownloadUpdates": true,
    "Language": "en",
    "Minimal": false,
    "RestrictedAddons": true,
    "Stages": {
      "0": "language",
      "18": "console_setup",
      "81": "console_setup",
      "123": "console_setup",
      "155": "console_setup",
      "168": "prepare",
      "256": "partman",
      "263": "partman",
      "264": "partman",
      "265": "partman",
      "299": "partman",
      "303": "partman",
      "311": "partman",
      "312": "partman",
      "324": "partman",
      "325": "start_install",
      "332": "timezone",
      "339": "usersetup",
      "351": "user_done",
      "551": "done"
    }
  }
}

```

**Comment by vitorgatti** [comment]
@vkareh if I don't set this value I get very big icons and fonts.

It doesn't matter if I set it to HiDPI ou Auto-Detect, the result is the same (fixes the issue with scaling).

If I logoff and logon with my user, the scaling gets corrupted again.

**Comment by shigutso** [comment]
Just to clarify, it's this option here that I have to change every time I login:

![image](https://user-images.githubusercontent.com/5687102/41508058-9b23c45c-7214-11e8-9585-74890b81f83b.png)

The **HiDPI** setting, I always have to change from **Regular** to **Auto-detect** and vice-versa after I login, or I get big fonts. If I choose HiDPI I get ginormous fonts, which is expected on my 1920x1080 display.

What's happening is that choosing Regular or Auto-detect is not being applied when I login. If there was a way to set it in the command line I could automate my login scripts, but for now I have to manually go to MATE-Tweak and change the settings every single time I turn on my computer :(

**Comment by vkareh** [comment]
This is a strange issue, but of you want to change it from the command line:
```
gsettings set org.mate.interface window-scaling-factor 0
```

* 0 is for auto-detect
* 1 is for Regular
* 2 is for HiDPI

**Comment by shigutso** [comment]
It only happens if I'm using nvidia's proprietary drivers. If using nouveau or intel onboard graphics (didn't test with amd because of lack of hardware), it works like it should. It's like there's something on nvidia's running before (or after) mate-tweak preventing it from using the correct settings.

Thanks for the command line options, I'll be using them for now :)

**Comment by akarelas** [comment]
I get the same error. I use nVidia's proprietary drivers with a 4k monitor (and also a HiDPI laptop screen at the same time, but issue still appears when using only the monitor). Whenever I log on to my account, I get a strange mixture of extra-large fonts with proper-sized HiDPI icons.

To fix my problem, every time I log on I open MATE Tweak, switch the HiDPI settings to 'normal', and then immediately back to 'HiDPI'. That fixed the problem.

To see what I mean by 'strange mixture' please see the attached screenshots in this message. Thank you.

This is the 'strange mixture' of extra-huge fonts with normal-sized icons I get whenever I log on:
![strange_dpi](https://user-images.githubusercontent.com/423822/60378649-156aba80-9a2e-11e9-8bfc-b44f645d9995.png)

And this is my Desktop with everything at its correct size:
![proper_HiDPI](https://user-images.githubusercontent.com/423822/60378650-1bf93200-9a2e-11e9-9075-4a778f95b2a2.png)

(Of course the above images appear twice the size of what they do on my screen, because they come from a capture of a 4k display. But you get my point).

**Comment by flexiondotorg** [comment]
The original reporter of this issue didn't have a HiDPI display, so not an actual issue in MATE Tweak or MATE.

As for the follow up regarding font size when using the nvidia driver, this is a long-standing issue with there driver which change the font dpi, for some reason. To fix it open Appearance Preferences, Fonts tab, click Details... button. Change the Dots per Inch (DPI) to something suitable for your display.
