### ISSUE TITLE
Add Disable Indicators option

### ISSUE THREAD

**Issue by danboid** [ubuntu-mate/mate-tweak#46]
Indicators are enabled by default under Ubuntu MATE 18.04 / MATE 1.20.1 but there doesn't seem to be any easy or obvious way to disable them other than deleting and re-creating the top panel but that doesn't disable the indicator startup apps. lukefromdc has since informed me that it can be done via org>mate>panel>general in dconf-editor and set enable-sni-support to false but that is very cryptic and not obvious in the slightest.

Unless there is a more logical place to include this option, I would like a quick and easy way to disable indicators with a single click under tweak.

**Comment by flexiondotorg** [comment]
Indicators are the default and only intended operation in Ubuntu MATE since the 18.04 release.
