### ISSUE TITLE
Please re-enable metacity and possibly marco-xcompmgr in the drop-down list of windows managers

### ISSUE THREAD

**Issue by DidierSpaier** [ubuntu-mate/mate-tweak#48]
Hello,

Using mate-tweak in Slint64-14.2.1.1 that ships compiz, marco, and metacity I noticed upgrading to mate-tweak 18.04.6 from  17.10.15 that in the drop-down list of window managers available for selection, metacity disappeared as well  as marco-xcompmgr.

This is unfortunate for us especially for metacity that we do ship.

I have found the commits involved in these removals, pasted below with email address removed:
commit 1b7e9af08bf0b4f0e70fe45253b636b5e41058f4
Author: Martin Wimpress
Date:   Sun Jan 21 21:06:58 2018 +0000
    Drop Metacity support.
commit 9268c5d1f61a9a88eea8f127c253707485259085
Author: Martin Wimpress
Date:   Sun Jan 21 21:12:56 2018 +0000
    Drop xcompmgr support.
commit f29e76bae85ab0ed34a1d80c8e83f2c3892d6304
Author: Martin Wimpress 
Date:   Mon Jan 22 02:28:56 2018 +0000
    Remove marco-xcompmgr from scripts.

Maybe Ubuntu doesn't provide metacity any more (I didn't check) but we do and want that our users be able to switch easily. I don't see any draw back re-enabling this possibility, as in case metacity is not installed it will not be proposed anyway.

Thanks.

**Comment by flexiondotorg** [comment]
Sorry, I don't have any plans to re-instate support for those components.

**Comment by DidierSpaier** [comment]
OK no worries, we'll ship both marco and compiz, which will be good enough as our users will be able to switch with mate-tweaks. Thanks for responding.
