### ISSUE TITLE
Default Compiz settings interfere with Global Menu layouts

### ISSUE THREAD

**Issue by mdmayfield** [ubuntu-mate/mate-tweak#50]
When using Compiz with default settings, and a panel layout that uses the global menu, menus can't "roll over" on the top pixel row of the screen. This is annoying at best and an accessibility issue at worst.

Demonstration in less than 20 seconds here: https://photos.google.com/share/AF1QipMKpPbnBy--HoYJ1JE4JNh4Yif2nCw28lzPsZ2BzlCIqJZPN9ox7kisU-HT2El2nA/photo/AF1QipNzMI_Vd4f1jhKSo91glNwIsTKnzC1jJWvAtUzi?key=VnppSmFqN0FLQmFHX0hpYkRxZHk5SmNvS3pDSjFB

This issue is caused by the Compiz setting **Desktop Wall -> Bindings -> Edge Flipping -> Flip Up** defaulting to **top**. If this is set to **none** the issue is resolved.

To fix this, the user must install CompizConfig Settings Manager, and also know to look at the Edge Flipping bindings.

To improve user-friendliness, I'd like to ask that you please consider automatically disabling the Edge Flipping mouse bindings (at least vertically) when Compiz is the active compositor and the user selects the Mutiny, Cupertino, or Contemporary layout.

Thank you!

Matt

----
For reference, here is an issue I filed earlier (which misidentified the cause and have since closed):
https://bugs.launchpad.net/ubuntu-mate/+bug/1754855

And here are two related, but not identical, issues which turned out to have yet a different cause.
https://github.com/rilian-la-te/vala-panel-appmenu/issues/208
https://github.com/mate-desktop/mate-panel/issues/741

**Comment by flexiondotorg** [comment]
Closing this as https://bugs.launchpad.net/ubuntu-mate/+bug/1754855 is the right place for this issue. It is not a MATE Tweak problem.
