### ISSUE TITLE
Panel Features grayed

### ISSUE THREAD

**Issue by doquen** [ubuntu-mate/mate-tweak#53]
Hi,
When i launch mate-tweak, some panel features are grayed out and i cannot select them. These are:

-Enable Indicators
-Enable Advanced Menu
-Activate Launcher
-Enable HUD
-Enable pull-down terminal

Any hits why?
Thanks in advance

**Comment by vkareh** [comment]
@PabloF7 - it's possible that you don't have the necessary packages. What version of UM are you using?
Try installing those apps: `sudo apt install mate-indicator-applet mate-menu mate-hud tilda`
