### ISSUE TITLE
Custom mutiny & netbook layouts require specific file names

### ISSUE THREAD

**Issue by etkeys** [ubuntu-mate/mate-tweak#56]
I use my laptop using dual external monitors or single onboard monitor configurations. I have two layouts that I swap between depending on what configuration I'm using at the time. Both layouts are based on Mutiny.  

Up until yesterday, whenever I switched between my two custom layouts, no matter which one I switch to or from, I would have to go Windows -> Window Behavior and check the box for `Undecorate maximized windows`. Looking at the code, I found out that this option was always being unchecked because the names of my custom layouts were not formatted correctly.  

mate-tweak requires that any custom layout that uses some default behaviors of Mutiny (e.g. Undecorate maximized windows), that the file name start with "mutiny". This requirement is not obvious to the user.

Additionally, this requirement seems too restrictive. Could "mutiny" appear anywhere in the file name and mate-tweak recognize that the user is applying a mutiny type layout?

The Netbook layout also is affected by a similar file name requirement.

This is on UbuntuMATE 18.04.1

**Comment by ilostmykeys88** [comment]
There's some recent activity here so I'll put this out there. I've started working on a change for this. I plan to have a pull request submitted by the end of the weekend.

**Comment by flexiondotorg** [comment]
CLosed via #57
