### ISSUE TITLE
Need instructions for use on other distributions

### ISSUE THREAD

**Issue by randallpittman** [ubuntu-mate/mate-tweak#59]
MATE can be used with other distros (e.g. CentOS), and mate-tweak can support operation on those distributions, but there should be instructions for installation. Here's what I had to do on CentOS 7.5.1804:
````bash
yum install python34 python34-pip python34-distutils-extra python34-psutil python34-setproctitle python34-gobject
cd ~/
git clone https://github.com/ubuntu-mate/mate-tweak.git
sudo python3 -m pip install mate-tweak
````

**Comment by flexiondotorg** [comment]
Please provide pull request to add install instructions for other distros. I only run Ubuntu and don't have the time to validate install steps on other distros. Sorry.
