### ISSUE TITLE
Marco-Compton black boxes

### ISSUE THREAD

**Issue by a-piece-of-garbage** [ubuntu-mate/mate-tweak#61]
I hope this is the correct place to post, this was the first DuckDuckGo result for "marco-compton github."
I'm using Debian Stable with MATE 1.16.2, so I don't know if it's been fixed yet, but whenever I launch an application from the panel, a black box appears behind it. I have tried to use my current icon and GTK themes as well as the default ones, with the same results.
Screenshot included.
![black box :(](https://user-images.githubusercontent.com/28831571/56178045-967cee80-5fb5-11e9-9bf0-c76685932429.png)

**Comment by flexiondotorg** [comment]
This was fixed some time ago but the version of Debian you are running doesn't include a version of MATE Tweak that includes the fix.
