### ISSUE TITLE
marco-compton doesn't work with newer compton

### ISSUE THREAD

**Issue by TrentSPalmer** [ubuntu-mate/mate-tweak#64]
Hello, marco-compton doesn't work compton 6.2 as is, because of changed options for compton.

In particular, `--vsync` no longer accepts arguments and this is fatal.  In addition, `--paint-on-overlay`, `--glx-swap-method undefined`, and `--clear-shadow` generate warnings because they are deprecated.

In the meantime, I have written [a comment](https://aur.archlinux.org/packages/mate-tweak/#comment-699955) for the mate-tweak package in the AUR, with a proposed fix.

Kind Regards, Trent

**Comment by TrentSPalmer** [comment]
So this bug doesn't affect ubuntu-mate.

According to the [Ubuntu Manpage](https://manpages.ubuntu.com/manpages/bionic/en/man1/compton.1.html), Ubuntu uses [chjj/compton](https://github.com/chjj/compton) for compton, whereas Arch uses [yshui/picom](https://github.com/yshui/picom) from compton.

**Comment by spvkgn** [comment]
Do you have any plans to get mate-tweak working with picom? Package `picom` available in Debian testing.

**Comment by satcom886** [comment]
Picom is pretty much the future of compton. Compton hasn't been updated in 3 years now and I think it's only a matter of time before picom gets to Ubuntu's repos. As @spvkgn mentioned, Debian already has picom in their testing repo.

**Comment by satcom886** [comment]
Oh by the way @TrentSPalmer, could you please resend your proposed solution somewhere, so I can use it? Your paste got deleted and I couldn't find it archived anywhere.

**Comment by TrentSPalmer** [comment]
Oh wow, thank you pastebin.  Looking at the configs on my rig you want to modify `/usr/bin/marco-compton`,

I changed `--vsync ${VSYNC} \` to `--vsync \`

and removed 
* `--paint-on-overlay \`
* `--glx-swap-method undefined \`
*  `--clear-shadow \`

**Comment by satcom886** [comment]
@TrentSPalmer That's actually much simpler than I expected!

Thank you so much for the reply!
