### ISSUE TITLE
More options for: Windows > Appearance > Window Control Placement

### ISSUE THREAD

**Issue by sixwheeledbeast** [ubuntu-mate/mate-tweak#65]
Probably more of a feature request than a bug.

Mate Tweak only supports Left and Right options for window control placement. 
These are a title bar button layout of  "menu:min,max,close" and "close,min,max:menu", if anything else has been set via dconf or a previous installations files this drop select box collapses to blank. 

dconf  "org/mate/marco/general/button-layout"

Firstly this should probably show something better than a empty drop down arrow if something different has been used.

![window_control_placement](https://user-images.githubusercontent.com/13704177/64078564-c2321400-cccb-11e9-8fd3-90f56d843a78.png)

In addition would be nice to have an option to support more settings. I would like an option to remove the window menu button for example, but maybe more options; like if "spacer" was used, could be supported somehow?

Current Left Preset
![titlebar_with_menu](https://user-images.githubusercontent.com/13704177/64078646-c01c8500-cccc-11e9-9281-801458c4aec2.png)

My preference without menu
![titlebar_without_menu](https://user-images.githubusercontent.com/13704177/64078648-c27edf00-cccc-11e9-93e8-724c0753ade5.png)

Left, spacer after close, no menu
![titlebar_with_spacer](https://user-images.githubusercontent.com/13704177/64078924-628a3780-ccd0-11e9-94a5-fb511d316b02.png)

**Comment by flexiondotorg** [comment]
This is an interesting idea :smiley: Your suggestion has prompted me to change the default window manager button layout in Ubuntu MATE 19.10 to not include the menu. This result in a much cleaner look. As you say the menu can still be accessed by right-clicking any window title are and also via <kbd>Alt</kbd> + <kbd>Space</kbd>.

I'll add some additional support for setting button layout either with or without the menu. I won't get into supporting spacers etc. For that advanced use case, there is `dconf-editor` :wink:
