### ISSUE TITLE
Could you please add KWin to the WM list?

### ISSUE THREAD

**Issue by CHJ85** [ubuntu-mate/mate-tweak#66]
Hi there.
I just replaced Marco with KWin.
I had to use the "kwin --replace" command, which is a bit of a dirty workaround.
But KWin wasn't in the Window Managers list.
So do you think you could add it please?

**Comment by flexiondotorg** [comment]
Sorry, no. This is not something I want to support.

**Comment by CHJ85** [comment]
Why is that?
