### ISSUE TITLE
mate-tweak-helper error in 19.10: 'org.mate.maximus' is not installed.

### ISSUE THREAD

**Issue by DeegC** [ubuntu-mate/mate-tweak#69]
MATE: 1.22.2
Ubuntu: 19.10

I use mate-tweak to edit/reset the panels in MATE from the command line and recently it stopped working after an update to 19.10.  I was able to track it down to mate-tweak-helper; when I run:

```mate-tweak-helper backup my-panel```

I get the following error:

```(process:22866): GLib-GIO-ERROR **: 20:01:01.943: Settings schema 'org.mate.maximus' is not installed```

I have no idea what org.mate.maximus is and haven't explicitly made any changes.  The error is generated in method ```get_maximus_undecorate()``` in the call to ```layout.extend```.  If I edit the method to just set ```layout.append('mate-maximus-recorded=False\n')``` everything works fine.

I don't know Python well enough to create a PR but maybe you can add the equivalent of try/catch here?  Let me know if I can help with more info.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-tweak/pull/82
