### ISSUE TITLE
"Change the layout" window pixel spacing is not right

### ISSUE THREAD

**Issue by stuartlangridge** [ubuntu-mate/mate-tweak#74]
This window:

![image](https://user-images.githubusercontent.com/4356350/79025820-cc2fc580-7b7e-11ea-84f9-1165d55ba6ea.png)

to me looks to have the wrong spacing. The text seems closer to the left and right edges of the window than it should be. I'm not sure what the numbers _should_ be, but it certainly looks wrong.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-tweak/commit/927b2ede5ec2042238f6da229e60a14ee7c124cf
