### ISSUE TITLE
can't find  munity

### ISSUE THREAD

**Issue by NoNameMan1231** [ubuntu-mate/mate-tweak#83]
when i want to change taskbr to munity mode ,  i realized it didn't available! it just have:
`gnome 2 ` `fedora` and `open suse`

help! i want to get munity back! :(

**Comment by clemzy666** [comment]
I have the same problem. It seems because of some packages needed for mutiny are missing ([see this topic](https://aur.archlinux.org/packages/mate-tweak/)) . However I didn't figure out how to add them.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-tweak/commit/1c62541529b14437422f97dcadd83cba0ee9d022
