### ISSUE TITLE
Picom Pantheon style dock issue

### ISSUE THREAD

**Issue by takov751** [ubuntu-mate/mate-tweak#85]
When any of the Picom compositor selected, the dock turns black. It's only occurs  when the screen where the dock is has no active window.
![image](https://user-images.githubusercontent.com/40316768/156497946-6cd39cfa-1397-45fc-9615-78c7c0fb05f2.png)

**Comment by flexiondotorg** [comment]
I have tested this on Ubuntu MATE 22.04 daily-live using all three Picom compositors and can not reproduce the issue.

**Comment by takov751** [comment]
I will test it tomorrow

**Comment by takov751** [comment]
![Screenshot at 2022-03-24 03-44-31](https://user-images.githubusercontent.com/40316768/159837960-80b048b7-abd8-4ed3-81dc-adfad97f3b63.png)
Tested again it's only appears in a weird edge case. where there is a game for example on non-primary monitor and after few alt-tabing this weird case appears. But it's only appeared after a while. I would say this is a bug, however it might be just an issue for a fraction of a user.
